export * from './core'
export { default as Authing } from './provider/Authing'
export { default as Gitee } from './provider/Gitee'
export { default as QQ } from './provider/QQ'
export { default as Wechat } from './provider/Wechat'
export { default as WechatMp } from './provider/WechatMp/index'
export * from './provider/WechatMp/WechatMpApi'
export * from './type'
