on:
  push:
    tags:
      - '*'
  workflow_dispatch:

name: publish-npm

jobs:
  publish-npm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: setup bun
        uses: oven-sh/setup-bun@v2

      - name: install app dependencies and build it
        run: bun i && pnpm run  build

      - name: publish to npm
        run: pnpm run  release
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
